/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
#include "lushconf.h"
#endif

/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"

/* ---------------------------------------- */

/*
 * FUNCTION pcloud-xyz2map
 */
extern_c char
C_pcloud_xyz2map (struct idx *L1_xyz, struct idx *L1_rgb, struct idx *L1_mp,
		  flt L1_cx, flt L1_cy, flt L1_ca, flt L1_sx, flt L1_sy,
		  flt L1_robot_height)
{
  TRACE_PUSH ("C_pcloud_xyz2map");
  {
    char L_Tmp0;
    {
      real L2_1_xmax;
      real L2_2_ymax;
      real L2_3_sx1;
      real L2_4_sy1;
      L2_1_xmax = (L1_mp)->dim[0];
      L2_2_ymax = (L1_mp)->dim[1];
      L2_3_sx1 = (-1 / (flt) L1_sx);
      L2_4_sy1 = (1 / (flt) L1_sy);
      {
	RTERR_LOOPDIM ((L1_rgb)->dim[0] != (L1_xyz)->dim[0]);
	Midx_begin_bloop2 (L3_xyz, L1_xyz, L3_rgb, L1_rgb, flt)
	{
	  {
	    real L4_5_z;
	    real L4_6_a2;
	    real L4_7_x2;
	    real L4_8_y2;
	    real L4_9_xx;
	    real L4_10_yy;
	    real L4_11_ixx;
	    real L4_12_iyy;
	    char L_Tmp13;
	    RTERR_BOUND (2 >= (&L3_xyz)->dim[0]);
	    L4_5_z = IDX_PTR (&L3_xyz, flt)[(&L3_xyz)->mod[0] * ((int) 2)];
	    L4_6_a2 = (L1_ca * (3.14 / (real) 180));
	    RTERR_BOUND (0 >= (&L3_xyz)->dim[0]);
	    RTERR_BOUND (1 >= (&L3_xyz)->dim[0]);
	    L4_7_x2 =
	      ((IDX_PTR (&L3_xyz, flt)[(&L3_xyz)->mod[0] * ((int) 0)] *
		Dcos (L4_6_a2)) - (IDX_PTR (&L3_xyz,
					    flt)[(&L3_xyz)->mod[0] *
						 ((int) 1)] *
				   Dsin (L4_6_a2)));
	    RTERR_BOUND (0 >= (&L3_xyz)->dim[0]);
	    RTERR_BOUND (1 >= (&L3_xyz)->dim[0]);
	    L4_8_y2 =
	      ((IDX_PTR (&L3_xyz, flt)[(&L3_xyz)->mod[0] * ((int) 0)] *
		Dsin (L4_6_a2)) + (IDX_PTR (&L3_xyz,
					    flt)[(&L3_xyz)->mod[0] *
						 ((int) 1)] *
				   Dcos (L4_6_a2)));
	    L4_9_xx = (L1_cx + (L4_7_x2 * L2_3_sx1));
	    L4_10_yy = (L1_cy + (L4_8_y2 * L2_4_sy1));
	    L4_11_ixx = L4_9_xx;
	    L4_11_ixx = ((int) floor ((double) L4_11_ixx));
	    L4_12_iyy = L4_10_yy;
	    L4_12_iyy = ((int) floor ((double) L4_12_iyy));
	    if ((L4_9_xx >= 0))
	      {
		if ((L4_9_xx < L2_1_xmax))
		  {
		    if ((L4_10_yy >= 0))
		      {
			if ((L4_10_yy < L2_2_ymax))
			  {
			    if ((L4_5_z < L1_robot_height))
			      {
				L_Tmp13 = 1;
			      }
			    else
			      {
				L_Tmp13 = 0;
			      }
			  }
			else
			  {
			    L_Tmp13 = 0;
			  }
		      }
		    else
		      {
			L_Tmp13 = 0;
		      }
		  }
		else
		  {
		    L_Tmp13 = 0;
		  }
	      }
	    else
	      {
		L_Tmp13 = 0;
	      }
	    if (L_Tmp13)
	      {
		RTERR_BOUND (L4_11_ixx < 0 || L4_11_ixx >= (L1_mp)->dim[0]);
		RTERR_BOUND (L4_12_iyy < 0 || L4_12_iyy >= (L1_mp)->dim[1]);
		RTERR_BOUND (0 >= (L1_mp)->dim[2]);
		RTERR_BOUND (L4_11_ixx < 0 || L4_11_ixx >= (L1_mp)->dim[0]);
		RTERR_BOUND (L4_12_iyy < 0 || L4_12_iyy >= (L1_mp)->dim[1]);
		RTERR_BOUND (0 >= (L1_mp)->dim[2]);
		IDX_PTR (L1_mp,
			 flt)[(L1_mp)->mod[0] * ((int) L4_11_ixx) +
			      (L1_mp)->mod[1] * ((int) L4_12_iyy) +
			      (L1_mp)->mod[2] * ((int) 0)] =
		  (IDX_PTR (L1_mp, flt)
		   [(L1_mp)->mod[0] * ((int) L4_11_ixx) +
		    (L1_mp)->mod[1] * ((int) L4_12_iyy) +
		    (L1_mp)->mod[2] * ((int) 0)] + 1);
		RTERR_BOUND (L4_11_ixx < 0 || L4_11_ixx >= (L1_mp)->dim[0]);
		RTERR_BOUND (L4_12_iyy < 0 || L4_12_iyy >= (L1_mp)->dim[1]);
		RTERR_BOUND (1 >= (L1_mp)->dim[2]);
		RTERR_BOUND (L4_11_ixx < 0 || L4_11_ixx >= (L1_mp)->dim[0]);
		RTERR_BOUND (L4_12_iyy < 0 || L4_12_iyy >= (L1_mp)->dim[1]);
		RTERR_BOUND (1 >= (L1_mp)->dim[2]);
		IDX_PTR (L1_mp,
			 flt)[(L1_mp)->mod[0] * ((int) L4_11_ixx) +
			      (L1_mp)->mod[1] * ((int) L4_12_iyy) +
			      (L1_mp)->mod[2] * ((int) 1)] =
		  (IDX_PTR (L1_mp, flt)
		   [(L1_mp)->mod[0] * ((int) L4_11_ixx) +
		    (L1_mp)->mod[1] * ((int) L4_12_iyy) +
		    (L1_mp)->mod[2] * ((int) 1)] + L4_5_z);
		RTERR_BOUND (L4_11_ixx < 0 || L4_11_ixx >= (L1_mp)->dim[0]);
		RTERR_BOUND (L4_12_iyy < 0 || L4_12_iyy >= (L1_mp)->dim[1]);
		RTERR_BOUND (2 >= (L1_mp)->dim[2]);
		RTERR_BOUND (L4_11_ixx < 0 || L4_11_ixx >= (L1_mp)->dim[0]);
		RTERR_BOUND (L4_12_iyy < 0 || L4_12_iyy >= (L1_mp)->dim[1]);
		RTERR_BOUND (2 >= (L1_mp)->dim[2]);
		IDX_PTR (L1_mp,
			 flt)[(L1_mp)->mod[0] * ((int) L4_11_ixx) +
			      (L1_mp)->mod[1] * ((int) L4_12_iyy) +
			      (L1_mp)->mod[2] * ((int) 2)] =
		  (IDX_PTR (L1_mp, flt)
		   [(L1_mp)->mod[0] * ((int) L4_11_ixx) +
		    (L1_mp)->mod[1] * ((int) L4_12_iyy) +
		    (L1_mp)->mod[2] * ((int) 2)] + (L4_5_z * L4_5_z));
	      }
	  }
	} Midx_end_bloop2 (L3_xyz, L1_xyz, L3_rgb, L1_rgb, flt);
      }
      L_Tmp0 = 0;
    }
    TRACE_POP ("C_pcloud_xyz2map");
    return 0;
  }
}

/*
 * FUNCTION map2cost
 */
extern_c char
C_map2cost (struct idx *L1_mp, struct idx *L1_im, flt L1_default_cost)
{
  TRACE_PUSH ("C_map2cost");
  {
    {
      real L2_0_v;
      L2_0_v = 0;
      {
	RTERR_LOOPDIM ((L1_im)->dim[0] != (L1_mp)->dim[0]);
	Midx_begin_bloop2 (L3_mp, L1_mp, L3_im, L1_im, flt)
	{
	  {
	    real L_Tmp1;
	    RTERR_LOOPDIM ((&L3_im)->dim[0] != (&L3_mp)->dim[0]);
	    Midx_begin_bloop2 (L4_mp, &L3_mp, L4_im, &L3_im, flt)
	    {
	      RTERR_BOUND (0 >= (&L4_mp)->dim[0]);
	      if ((0 == IDX_PTR (&L4_mp, flt)[(&L4_mp)->mod[0] * ((int) 0)]))
		{
		  RTERR_BOUND (0 >= (&L4_im)->dim[0]);
		  IDX_PTR (&L4_im, flt)[(&L4_im)->mod[0] * ((int) 0)] =
		    L1_default_cost;
		  RTERR_BOUND (1 >= (&L4_im)->dim[0]);
		  IDX_PTR (&L4_im, flt)[(&L4_im)->mod[0] * ((int) 1)] = 0;
		}
	      else
		{
		  RTERR_BOUND (0 >= (&L4_im)->dim[0]);
		  RTERR_BOUND (1 >= (&L4_mp)->dim[0]);
		  RTERR_BOUND (0 >= (&L4_mp)->dim[0]);
		  IDX_PTR (&L4_im, flt)[(&L4_im)->mod[0] * ((int) 0)] =
		    ((-IDX_PTR (&L4_mp, flt)[(&L4_mp)->mod[0] * ((int) 1)]) /
		     (flt) IDX_PTR (&L4_mp,
				    flt)[(&L4_mp)->mod[0] * ((int) 0)]);
		  RTERR_BOUND (1 >= (&L4_im)->dim[0]);
		  {
		    real L5_2_a;
		    real L5_3_b;
		    L5_2_a = 1;
		    RTERR_BOUND (0 >= (&L4_mp)->dim[0]);
		    L5_3_b =
		      (IDX_PTR (&L4_mp, flt)[(&L4_mp)->mod[0] * ((int) 0)] *
		       100);
		    if ((L5_2_a < L5_3_b))
		      {
			L_Tmp1 = L5_2_a;
		      }
		    else
		      {
			L_Tmp1 = L5_3_b;
		      }
		  }
		  IDX_PTR (&L4_im, flt)[(&L4_im)->mod[0] * ((int) 1)] =
		    L_Tmp1;
		}
	    } Midx_end_bloop2 (L4_mp, &L3_mp, L4_im, &L3_im, flt);
	  }
	} Midx_end_bloop2 (L3_mp, L1_mp, L3_im, L1_im, flt);
      }
    }
    TRACE_POP ("C_map2cost");
    return 0;
  }
}

/*
 * FUNCTION costmap2image
 */
extern_c struct idx *
C_costmap2image (struct idx *L1_mp, struct idx *L1_im, flt L1_vv)
{
  TRACE_PUSH ("C_costmap2image");
  {
    struct idx *L_Tmp0;
    {
      real L2_1_v;
      L2_1_v = 0;
      {
	RTERR_LOOPDIM ((L1_im)->dim[0] != (L1_mp)->dim[0]);
	Midx_begin_bloop2 (L3_mp, L1_mp, L3_im, L1_im, unsigned char)
	{
	  {
	    RTERR_LOOPDIM ((&L3_im)->dim[0] != (&L3_mp)->dim[0]);
	    Midx_begin_bloop2 (L4_mp, &L3_mp, L4_im, &L3_im, unsigned char)
	    {
	      RTERR_BOUND (1 >= (&L4_mp)->dim[0]);
	      if ((0 == IDX_PTR (&L4_mp, flt)[(&L4_mp)->mod[0] * ((int) 1)]))
		{
		  RTERR_BOUND (0 >= (&L4_im)->dim[0]);
		  IDX_PTR (&L4_im,
			   unsigned char)[(&L4_im)->mod[0] * ((int) 0)] = 0;
		  RTERR_BOUND (1 >= (&L4_im)->dim[0]);
		  IDX_PTR (&L4_im,
			   unsigned char)[(&L4_im)->mod[0] * ((int) 1)] = 0;
		  RTERR_BOUND (2 >= (&L4_im)->dim[0]);
		  IDX_PTR (&L4_im,
			   unsigned char)[(&L4_im)->mod[0] * ((int) 2)] = 200;
		}
	      else
		{
		  RTERR_BOUND (1 >= (&L4_mp)->dim[0]);
		  if ((10 ==
		       IDX_PTR (&L4_mp, flt)[(&L4_mp)->mod[0] * ((int) 1)]))
		    {
		      RTERR_BOUND (0 >= (&L4_im)->dim[0]);
		      IDX_PTR (&L4_im,
			       unsigned char)[(&L4_im)->mod[0] * ((int) 0)] =
			200;
		      RTERR_BOUND (1 >= (&L4_im)->dim[0]);
		      IDX_PTR (&L4_im,
			       unsigned char)[(&L4_im)->mod[0] * ((int) 1)] =
			0;
		      RTERR_BOUND (2 >= (&L4_im)->dim[0]);
		      IDX_PTR (&L4_im,
			       unsigned char)[(&L4_im)->mod[0] * ((int) 2)] =
			0;
		    }
		  else
		    {
		      {
			real L5_2_a;
			real L5_3_b;
			L5_2_a = 255;
			{
			  real L6_4_a;
			  real L6_5_b;
			  L6_4_a = 0;
			  RTERR_BOUND (0 >= (&L4_mp)->dim[0]);
			  L6_5_b =
			    ((255 / (flt) L1_vv) *
			     IDX_PTR (&L4_mp,
				      flt)[(&L4_mp)->mod[0] * ((int) 0)]);
			  if ((L6_4_a > L6_5_b))
			    {
			      L5_3_b = L6_4_a;
			    }
			  else
			    {
			      L5_3_b = L6_5_b;
			    }
			}
			if ((L5_2_a < L5_3_b))
			  {
			    L2_1_v = L5_2_a;
			  }
			else
			  {
			    L2_1_v = L5_3_b;
			  }
		      }
		      RTERR_BOUND (0 >= (&L4_im)->dim[0]);
		      IDX_PTR (&L4_im,
			       unsigned char)[(&L4_im)->mod[0] * ((int) 0)] =
			L2_1_v;
		      RTERR_BOUND (1 >= (&L4_im)->dim[0]);
		      IDX_PTR (&L4_im,
			       unsigned char)[(&L4_im)->mod[0] * ((int) 1)] =
			L2_1_v;
		      RTERR_BOUND (2 >= (&L4_im)->dim[0]);
		      IDX_PTR (&L4_im,
			       unsigned char)[(&L4_im)->mod[0] * ((int) 2)] =
			L2_1_v;
		    }
		}
	    } Midx_end_bloop2 (L4_mp, &L3_mp, L4_im, &L3_im, unsigned char);
	  }
	} Midx_end_bloop2 (L3_mp, L1_mp, L3_im, L1_im, unsigned char);
	L_Tmp0 = L1_im;
      }
    }
    TRACE_POP ("C_costmap2image");
    return L_Tmp0;
  }
}

/*
 * FUNCTION mark-ground
 */
extern_c struct idx *
C_mark_ground (struct idx *L1_xyz, struct idx *L1_rcd, struct idx *L1_image,
	       flt L1_th, flt L1_rh, struct idx *L3_0_matrix,
	       struct srg *L3_0_srg)
{
  TRACE_PUSH ("C_mark_ground");
  {
    struct idx *L_Tmp0;
    {
      real L2_1_imax;
      struct idx *L2_2_newimage;
      L2_1_imax = (L1_xyz)->dim[0];
      {
	struct idx *L3_3_out;
	(L3_0_matrix)->srg = L3_0_srg;
	Midx_init_dim3 (L3_0_matrix, (L1_image)->dim[0], (L1_image)->dim[1],
			(L1_image)->dim[2]);
	RTERR_DIM (L3_0_matrix->dim[0] <= 0);
	RTERR_DIM (L3_0_matrix->dim[1] <= 0);
	RTERR_DIM (L3_0_matrix->dim[2] <= 0);
	L3_3_out = L3_0_matrix;
	{
	  RTERR_LOOPDIM ((L3_3_out)->dim[0] != (L1_image)->dim[0]);
	  Midx_begin_bloop2 (L4_in, L1_image, L4_out, L3_3_out, unsigned char)
	  {
	    check_main_maout (&L4_in, &L4_out);
	    Midx_m2copy (&L4_in, &L4_out, unsigned char, unsigned char);
	  } Midx_end_bloop2 (L4_in, L1_image, L4_out, L3_3_out,
			     unsigned char);
	  L2_2_newimage = L3_3_out;
	}
      }
      {
	real L3_4_i;
	real L_Tmp5;
	L_Tmp5 = ((L2_1_imax) - 1);
	L3_4_i = 0;
	for (;
	     ((1 > 0) ? (L3_4_i <= L_Tmp5) : (L3_4_i >= L_Tmp5));
	     (L3_4_i) += 1)
	  {
	    {
	      real L4_6_z;
	      real L4_7_xx;
	      real L4_8_yy;
	      L4_6_z = 0;
	      L4_7_xx = 0;
	      L4_8_yy = 0;
	      RTERR_BOUND (L3_4_i < 0 || L3_4_i >= (L1_xyz)->dim[0]);
	      RTERR_BOUND (2 >= (L1_xyz)->dim[1]);
	      L4_6_z =
		(L1_rh +
		 (-IDX_PTR (L1_xyz, flt)
		  [(L1_xyz)->mod[0] * ((int) L3_4_i) +
		   (L1_xyz)->mod[1] * ((int) 2)]));
	      RTERR_BOUND (L3_4_i < 0 || L3_4_i >= (L1_rcd)->dim[0]);
	      RTERR_BOUND (1 >= (L1_rcd)->dim[1]);
	      L4_7_xx =
		IDX_PTR (L1_rcd,
			 flt)[(L1_rcd)->mod[0] * ((int) L3_4_i) +
			      (L1_rcd)->mod[1] * ((int) 1)];
	      RTERR_BOUND (L3_4_i < 0 || L3_4_i >= (L1_rcd)->dim[0]);
	      RTERR_BOUND (0 >= (L1_rcd)->dim[1]);
	      L4_8_yy =
		IDX_PTR (L1_rcd,
			 flt)[(L1_rcd)->mod[0] * ((int) L3_4_i) +
			      (L1_rcd)->mod[1] * ((int) 0)];
	      if ((L4_6_z < L1_th))
		{
		  RTERR_BOUND (L4_8_yy < 0
			       || L4_8_yy >= (L2_2_newimage)->dim[0]);
		  RTERR_BOUND (L4_7_xx < 0
			       || L4_7_xx >= (L2_2_newimage)->dim[1]);
		  RTERR_BOUND (1 >= (L2_2_newimage)->dim[2]);
		  IDX_PTR (L2_2_newimage,
			   unsigned char)[(L2_2_newimage)->mod[0] *
					  ((int) L4_8_yy) +
					  (L2_2_newimage)->mod[1] *
					  ((int) L4_7_xx) +
					  (L2_2_newimage)->mod[2] *
					  ((int) 1)] = 0;
		}
	    }
	  }
      }
      L_Tmp0 = L2_2_newimage;
    }
    TRACE_POP ("C_mark_ground");
    return L_Tmp0;
  }
}

/* ---------------------------------------- */

#ifndef NOLISP

/*
 * STUB pcloud-xyz2map
 */
DH (X_pcloud_xyz2map)
{
  dharg ret;
  ret.dh_char =
    C_pcloud_xyz2map (a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr,
		      a[4].dh_flt, a[5].dh_flt, a[6].dh_flt, a[7].dh_flt,
		      a[8].dh_flt, a[9].dh_flt);
  return ret;
}

/*
 * DHDOC pcloud-xyz2map
 */
DHDOC (K_pcloud_xyz2map_Raf9766c2, X_pcloud_xyz2map, "C_pcloud_xyz2map", 0,
       0) =
{
DH_FUNC (9),
    DH_IDX (DHT_READ, 2),
    DH_SRG (DHT_READ),
    DH_FLT,
    DH_IDX (DHT_READ, 2),
    DH_SRG (DHT_READ),
    DH_FLT,
    DH_IDX (DHT_READ, 3),
    DH_SRG (DHT_WRITE),
    DH_FLT,
    DH_FLT,
    DH_FLT,
    DH_FLT, DH_FLT, DH_FLT, DH_FLT, DH_RETURN, DH_NIL, DH_END_FUNC, DH_NIL};

/*
 * STUB map2cost
 */
DH (X_map2cost)
{
  dharg ret;
  ret.dh_char = C_map2cost (a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_flt);
  return ret;
}

/*
 * DHDOC map2cost
 */
DHDOC (K_map2cost_R3dad9754, X_map2cost, "C_map2cost", 0, 0) =
{
DH_FUNC (3),
    DH_IDX (DHT_READ, 3),
    DH_SRG (DHT_READ),
    DH_FLT,
    DH_IDX (DHT_READ, 3),
    DH_SRG (DHT_READ),
    DH_FLT, DH_FLT, DH_RETURN, DH_NIL, DH_END_FUNC, DH_NIL};

/*
 * STUB costmap2image
 */
DH (X_costmap2image)
{
  dharg ret;
  ret.dh_idx_ptr =
    C_costmap2image (a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_flt);
  return ret;
}

/*
 * DHDOC costmap2image
 */
DHDOC (K_costmap2image_R16960b38, X_costmap2image, "C_costmap2image", 0, 0) =
{
DH_FUNC (3),
    DH_IDX (DHT_READ, 3),
    DH_SRG (DHT_READ),
    DH_FLT,
    DH_IDX (DHT_READ, 3),
    DH_SRG (DHT_READ),
    DH_UBYTE,
    DH_FLT,
    DH_RETURN,
    DH_IDX (DHT_READ, 3), DH_SRG (DHT_READ), DH_UBYTE, DH_END_FUNC, DH_NIL};

/*
 * STUB mark-ground
 */
DH (X_mark_ground)
{
  dharg ret;
  ret.dh_idx_ptr =
    C_mark_ground (a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr,
		   a[4].dh_flt, a[5].dh_flt, a[6].dh_idx_ptr,
		   a[7].dh_srg_ptr);
  return ret;
}

/*
 * DHDOC mark-ground
 */
DHDOC (K_mark_ground_R1fa2d4b1, X_mark_ground, "C_mark_ground", 0, 0) =
{
DH_FUNC (5),
    DH_IDX (DHT_READ, 2),
    DH_SRG (DHT_READ),
    DH_FLT,
    DH_IDX (DHT_READ, 2),
    DH_SRG (DHT_READ),
    DH_FLT,
    DH_IDX (DHT_READ, 3),
    DH_SRG (DHT_READ),
    DH_UBYTE,
    DH_FLT,
    DH_FLT,
    DH_TEMPS (2),
    DH_IDX (DHT_WRITE, 3), DH_UBYTE,
    DH_SRG (DHT_WRITE), DH_UBYTE,
    DH_END_TEMPS,
    DH_RETURN,
    DH_IDX (DHT_READ, 3), DH_SRG (DHT_WRITE), DH_UBYTE, DH_END_FUNC, DH_NIL};

/*
 * INIT FUNCTION
 */
extern_c void
init_demo_dai (void)
{
  dh_define ("pcloud-xyz2map", &K_pcloud_xyz2map_Raf9766c2);
  dh_define ("map2cost", &K_map2cost_R3dad9754);
  dh_define ("costmap2image", &K_costmap2image_R16960b38);
  dh_define ("mark-ground", &K_mark_ground_R1fa2d4b1);
}

int majver_demo_dai = 40;
int minver_demo_dai = 10;

#endif
