/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
#include "lushconf.h"
#endif

/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"

/* ---------------------------------------- */

/*
 * FUNCTION pcloud-xyz2rc
 */
extern_c struct idx *
C_pcloud_xyz2rc (struct idx *L1_xyz, struct idx *L1_rc, struct idx *L1_pr,
		 struct idx *L1_pt, struct idx *L1_pxyz2rc,
		 struct idx *L2_2_matrix, struct srg *L2_2_srg)
{
  TRACE_PUSH ("C_pcloud_xyz2rc");
  {
    struct idx *L_Tmp0;
    Midx_declare (L1_1_0_matrix, 2);
    Msrg_declare (L1_2_0_srg);
    Midx_init (L1_1_0_matrix, 2);
    Msrg_init (L1_2_0_srg, ST_F);
    (L1_1_0_matrix)->srg = L1_2_0_srg;
    Midx_init_dim2 (L1_1_0_matrix, (L1_xyz)->dim[0], 2);
    RTERR_DIM (L1_1_0_matrix->dim[0] <= 0);
    RTERR_DIM (L1_1_0_matrix->dim[1] <= 0);
    Midx_maclear (L1_1_0_matrix, flt);
    L1_rc = L1_1_0_matrix;
    {
      Midx_declare (L3_3_1_matrix, 2);
      Msrg_declare (L3_4_1_srg);
      struct idx *L2_5_xyz2;
      struct idx *L2_6_rcxyz;
      Midx_init (L3_3_1_matrix, 2);
      Msrg_init (L3_4_1_srg, ST_F);
      {
	(L3_3_1_matrix)->srg = L3_4_1_srg;
	Midx_init_dim2 (L3_3_1_matrix, (L1_xyz)->dim[0], (L1_xyz)->dim[1]);
	RTERR_DIM (L3_3_1_matrix->dim[0] <= 0);
	RTERR_DIM (L3_3_1_matrix->dim[1] <= 0);
	check_main_maout (L1_xyz, L3_3_1_matrix);
	Midx_m2copy (L1_xyz, L3_3_1_matrix, flt, flt);
	L2_5_xyz2 = L3_3_1_matrix;
      }
      (L2_2_matrix)->srg = L2_2_srg;
      Midx_init_dim2 (L2_2_matrix, (L1_xyz)->dim[0], 5);
      RTERR_DIM (L2_2_matrix->dim[0] <= 0);
      RTERR_DIM (L2_2_matrix->dim[1] <= 0);
      Midx_maclear (L2_2_matrix, flt);
      L2_6_rcxyz = L2_2_matrix;
      {
	RTERR_LOOPDIM ((L2_6_rcxyz)->dim[0] != (L1_rc)->dim[0]
		       || (L2_6_rcxyz)->dim[0] != (L1_xyz)->dim[0]
		       || (L2_6_rcxyz)->dim[0] != (L2_5_xyz2)->dim[0]);
	Midx_begin_bloop4 (L3_xyz2, L2_5_xyz2, L3_xyz, L1_xyz, L3_rc, L1_rc,
			   L3_rcxyz, L2_6_rcxyz, flt)
	{
	  RTERR_BOUND (0 >= (&L3_xyz2)->dim[0]);
	  RTERR_BOUND (0 >= (&L3_xyz)->dim[0]);
	  RTERR_BOUND (0 >= (L1_pr)->dim[0]);
	  RTERR_BOUND (0 >= (L1_pr)->dim[1]);
	  RTERR_BOUND (1 >= (&L3_xyz)->dim[0]);
	  RTERR_BOUND (1 >= (L1_pr)->dim[0]);
	  RTERR_BOUND (0 >= (L1_pr)->dim[1]);
	  RTERR_BOUND (2 >= (&L3_xyz)->dim[0]);
	  RTERR_BOUND (2 >= (L1_pr)->dim[0]);
	  RTERR_BOUND (0 >= (L1_pr)->dim[1]);
	  RTERR_BOUND (0 >= (L1_pt)->dim[0]);
	  IDX_PTR (&L3_xyz2, flt)[(&L3_xyz2)->mod[0] * ((int) 0)] =
	    ((IDX_PTR (&L3_xyz, flt)[(&L3_xyz)->mod[0] * ((int) 0)] *
	      IDX_PTR (L1_pr,
		       flt)[(L1_pr)->mod[0] * ((int) 0) +
			    (L1_pr)->mod[1] * ((int) 0)]) + (IDX_PTR (&L3_xyz,
								      flt)[(&L3_xyz)->mod[0] * ((int) 1)] * IDX_PTR (L1_pr, flt)[(L1_pr)->mod[0] * ((int) 1) + (L1_pr)->mod[1] * ((int) 0)]) + (IDX_PTR (&L3_xyz, flt)[(&L3_xyz)->mod[0] * ((int) 2)] * IDX_PTR (L1_pr, flt)[(L1_pr)->mod[0] * ((int) 2) + (L1_pr)->mod[1] * ((int) 0)]) + IDX_PTR (L1_pt, flt)[(L1_pt)->mod[0] * ((int) 0)]);
	  RTERR_BOUND (1 >= (&L3_xyz2)->dim[0]);
	  RTERR_BOUND (0 >= (&L3_xyz)->dim[0]);
	  RTERR_BOUND (0 >= (L1_pr)->dim[0]);
	  RTERR_BOUND (1 >= (L1_pr)->dim[1]);
	  RTERR_BOUND (1 >= (&L3_xyz)->dim[0]);
	  RTERR_BOUND (1 >= (L1_pr)->dim[0]);
	  RTERR_BOUND (1 >= (L1_pr)->dim[1]);
	  RTERR_BOUND (2 >= (&L3_xyz)->dim[0]);
	  RTERR_BOUND (2 >= (L1_pr)->dim[0]);
	  RTERR_BOUND (1 >= (L1_pr)->dim[1]);
	  RTERR_BOUND (1 >= (L1_pt)->dim[0]);
	  IDX_PTR (&L3_xyz2, flt)[(&L3_xyz2)->mod[0] * ((int) 1)] =
	    ((IDX_PTR (&L3_xyz, flt)[(&L3_xyz)->mod[0] * ((int) 0)] *
	      IDX_PTR (L1_pr,
		       flt)[(L1_pr)->mod[0] * ((int) 0) +
			    (L1_pr)->mod[1] * ((int) 1)]) + (IDX_PTR (&L3_xyz,
								      flt)[(&L3_xyz)->mod[0] * ((int) 1)] * IDX_PTR (L1_pr, flt)[(L1_pr)->mod[0] * ((int) 1) + (L1_pr)->mod[1] * ((int) 1)]) + (IDX_PTR (&L3_xyz, flt)[(&L3_xyz)->mod[0] * ((int) 2)] * IDX_PTR (L1_pr, flt)[(L1_pr)->mod[0] * ((int) 2) + (L1_pr)->mod[1] * ((int) 1)]) + IDX_PTR (L1_pt, flt)[(L1_pt)->mod[0] * ((int) 1)]);
	  RTERR_BOUND (2 >= (&L3_xyz2)->dim[0]);
	  RTERR_BOUND (0 >= (&L3_xyz)->dim[0]);
	  RTERR_BOUND (0 >= (L1_pr)->dim[0]);
	  RTERR_BOUND (2 >= (L1_pr)->dim[1]);
	  RTERR_BOUND (1 >= (&L3_xyz)->dim[0]);
	  RTERR_BOUND (1 >= (L1_pr)->dim[0]);
	  RTERR_BOUND (2 >= (L1_pr)->dim[1]);
	  RTERR_BOUND (2 >= (&L3_xyz)->dim[0]);
	  RTERR_BOUND (2 >= (L1_pr)->dim[0]);
	  RTERR_BOUND (2 >= (L1_pr)->dim[1]);
	  RTERR_BOUND (2 >= (L1_pt)->dim[0]);
	  IDX_PTR (&L3_xyz2, flt)[(&L3_xyz2)->mod[0] * ((int) 2)] =
	    ((IDX_PTR (&L3_xyz, flt)[(&L3_xyz)->mod[0] * ((int) 0)] *
	      IDX_PTR (L1_pr,
		       flt)[(L1_pr)->mod[0] * ((int) 0) +
			    (L1_pr)->mod[1] * ((int) 2)]) + (IDX_PTR (&L3_xyz,
								      flt)[(&L3_xyz)->mod[0] * ((int) 1)] * IDX_PTR (L1_pr, flt)[(L1_pr)->mod[0] * ((int) 1) + (L1_pr)->mod[1] * ((int) 2)]) + (IDX_PTR (&L3_xyz, flt)[(&L3_xyz)->mod[0] * ((int) 2)] * IDX_PTR (L1_pr, flt)[(L1_pr)->mod[0] * ((int) 2) + (L1_pr)->mod[1] * ((int) 2)]) + IDX_PTR (L1_pt, flt)[(L1_pt)->mod[0] * ((int) 2)]);
	  RTERR_BOUND (1 >= (&L3_rc)->dim[0]);
	  RTERR_BOUND (0 >= (&L3_xyz2)->dim[0]);
	  RTERR_BOUND (0 >= (L1_pxyz2rc)->dim[0]);
	  RTERR_BOUND (2 >= (&L3_xyz2)->dim[0]);
	  RTERR_BOUND (2 >= (L1_pxyz2rc)->dim[0]);
	  IDX_PTR (&L3_rc, flt)[(&L3_rc)->mod[0] * ((int) 1)] =
	    (int) ((((IDX_PTR (&L3_xyz2, flt)[(&L3_xyz2)->mod[0] * ((int) 0)]
		      * IDX_PTR (L1_pxyz2rc,
				 flt)[(L1_pxyz2rc)->mod[0] * ((int) 0)]) /
		     (flt) IDX_PTR (&L3_xyz2,
				    flt)[(&L3_xyz2)->mod[0] * ((int) 2)]) +
		    IDX_PTR (L1_pxyz2rc,
			     flt)[(L1_pxyz2rc)->mod[0] * ((int) 2)]));
	  RTERR_BOUND (0 >= (&L3_rc)->dim[0]);
	  RTERR_BOUND (1 >= (&L3_xyz2)->dim[0]);
	  RTERR_BOUND (1 >= (L1_pxyz2rc)->dim[0]);
	  RTERR_BOUND (2 >= (&L3_xyz2)->dim[0]);
	  RTERR_BOUND (3 >= (L1_pxyz2rc)->dim[0]);
	  IDX_PTR (&L3_rc, flt)[(&L3_rc)->mod[0] * ((int) 0)] =
	    (int) ((((IDX_PTR (&L3_xyz2, flt)[(&L3_xyz2)->mod[0] * ((int) 1)]
		      * IDX_PTR (L1_pxyz2rc,
				 flt)[(L1_pxyz2rc)->mod[0] * ((int) 1)]) /
		     (flt) IDX_PTR (&L3_xyz2,
				    flt)[(&L3_xyz2)->mod[0] * ((int) 2)]) +
		    IDX_PTR (L1_pxyz2rc,
			     flt)[(L1_pxyz2rc)->mod[0] * ((int) 3)]));
	  RTERR_BOUND (0 >= (&L3_rcxyz)->dim[0]);
	  RTERR_BOUND (0 >= (&L3_rc)->dim[0]);
	  IDX_PTR (&L3_rcxyz, flt)[(&L3_rcxyz)->mod[0] * ((int) 0)] =
	    IDX_PTR (&L3_rc, flt)[(&L3_rc)->mod[0] * ((int) 0)];
	  RTERR_BOUND (1 >= (&L3_rcxyz)->dim[0]);
	  RTERR_BOUND (1 >= (&L3_rc)->dim[0]);
	  IDX_PTR (&L3_rcxyz, flt)[(&L3_rcxyz)->mod[0] * ((int) 1)] =
	    IDX_PTR (&L3_rc, flt)[(&L3_rc)->mod[0] * ((int) 1)];
	  RTERR_BOUND (2 >= (&L3_rcxyz)->dim[0]);
	  RTERR_BOUND (0 >= (&L3_xyz)->dim[0]);
	  IDX_PTR (&L3_rcxyz, flt)[(&L3_rcxyz)->mod[0] * ((int) 2)] =
	    IDX_PTR (&L3_xyz, flt)[(&L3_xyz)->mod[0] * ((int) 0)];
	  RTERR_BOUND (3 >= (&L3_rcxyz)->dim[0]);
	  RTERR_BOUND (1 >= (&L3_xyz)->dim[0]);
	  IDX_PTR (&L3_rcxyz, flt)[(&L3_rcxyz)->mod[0] * ((int) 3)] =
	    IDX_PTR (&L3_xyz, flt)[(&L3_xyz)->mod[0] * ((int) 1)];
	  RTERR_BOUND (4 >= (&L3_rcxyz)->dim[0]);
	  RTERR_BOUND (2 >= (&L3_xyz)->dim[0]);
	  IDX_PTR (&L3_rcxyz, flt)[(&L3_rcxyz)->mod[0] * ((int) 4)] =
	    IDX_PTR (&L3_xyz, flt)[(&L3_xyz)->mod[0] * ((int) 2)];
	} Midx_end_bloop4 (L3_xyz2, L2_5_xyz2, L3_xyz, L1_xyz, L3_rc, L1_rc,
			   L3_rcxyz, L2_6_rcxyz, flt);
      }
      L_Tmp0 = L2_6_rcxyz;
      Msrg_free (L3_4_1_srg);
    }
    Msrg_free (L1_2_0_srg);
    TRACE_POP ("C_pcloud_xyz2rc");
    return L_Tmp0;
  }
}

/* ---------------------------------------- */

#ifndef NOLISP

/*
 * STUB pcloud-xyz2rc
 */
DH (X_pcloud_xyz2rc)
{
  dharg ret;
  ret.dh_idx_ptr =
    C_pcloud_xyz2rc (a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr,
		     a[4].dh_idx_ptr, a[5].dh_idx_ptr, a[6].dh_idx_ptr,
		     a[7].dh_srg_ptr);
  return ret;
}

/*
 * DHDOC pcloud-xyz2rc
 */
DHDOC (K_pcloud_xyz2rc_R7177dc08, X_pcloud_xyz2rc, "C_pcloud_xyz2rc", 0, 0) =
{
DH_FUNC (5),
    DH_IDX (DHT_READ, 2),
    DH_SRG (DHT_READ),
    DH_FLT,
    DH_IDX (DHT_READ, 2),
    DH_SRG (DHT_READ),
    DH_FLT,
    DH_IDX (DHT_READ, 2),
    DH_SRG (DHT_READ),
    DH_FLT,
    DH_IDX (DHT_READ, 1),
    DH_SRG (DHT_READ),
    DH_FLT,
    DH_IDX (DHT_READ, 1),
    DH_SRG (DHT_READ),
    DH_FLT,
    DH_TEMPS (2),
    DH_IDX (DHT_WRITE, 2), DH_FLT,
    DH_SRG (DHT_WRITE), DH_FLT,
    DH_END_TEMPS,
    DH_RETURN,
    DH_IDX (DHT_READ, 2), DH_SRG (DHT_READ), DH_FLT, DH_END_FUNC, DH_NIL};

/*
 * INIT FUNCTION
 */
extern_c void
init_pcloud2 (void)
{
  dh_define ("pcloud-xyz2rc", &K_pcloud_xyz2rc_R7177dc08);
}

int majver_pcloud2 = 40;
int minver_pcloud2 = 10;

#endif
